### ISSUE TITLE
Final Sprint

### ISSUE THREAD

**Issue by Kahuna915** [Kahuna915/Capstone-Design#24]
# Deliverable Statements
In this sprint, we plan on cleaning up Cyber.AWS. We are looking to do quality assurance on all of the work done in the previous sprints along with cleaning up the documentation. If anything task in the previous sprints was not completed, it will become a top priority for this sprint.

# Objectective & Discrete Tasks
Objectives & Discrete Tasks are listed below throughout the weeks

# Week 10
Week 10, we will start our quality control process for our security groups, access control lists, and organizational units
-  [x] [Quality assurance for security groups](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/30)         (Tanner and Noah)
-  [x] [Quality assurance for access control lists](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/30)    (Tanner and Noah)
-  [x] [Quality assurance for organizational units](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/30)  (Tanner and Noah)
-  [x] [Working on setting up credits for students](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/30) (Tanner and Noah)
- [x] [Limits are in place](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/30)                                         (Tanner and Noah)
## Kickoff meeting
A meeting took place on Monday the 10th to discuss the objective of our final sprint. 

# Week 11
In week 11, we will need to perform quality control for our budgeting as well as admin logging
- [ ] [Budget reports are sent to the correct emails](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/31) (Tanner and Noah)
- [x] [Correct Champlain Faculty have access](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/31) (Tanner and Noah)

## Progress update
At the end of week 11, we will need to do a progress update to make sure the team is at a good point.

# Week 12
In Week 12, we will fix GitHub up and work on the final presentation. 
- [x] [Clean up Github](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/32) (Noah)
- [x] [Presentation/Powerpoint](https://github.com/Kahuna915/Capstone-Cloud-Integration/issues/32) (Everyone)
- [x] [Admin to select student group] (Everyone)

## Progress Update
Week 12 progress update to see

# Demo
Our demo will be the foundation of our organization. Users, Organizational Units, AD joined, budget reports, and propagated billing for users.

### Reflection
How did the sprint go?  
The sprint went well. It was all wrapped up nicely with the github being updated and our slides completed.
